<?php
/*
 * @package     Intelipost_Pickup
 * @copyright   Copyright (c) 2016 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<script>

var INTELIPOST_PICKUP_STORE_URL = "<?php echo $this->getAjaxStoreUrl(); ?>";
var INTELIPOST_PICKUP_CITIES_URL = "<?php echo $this->getAjaxCitiesUrl(); ?>";
var INTELIPOST_PICKUP_PUDO_URL = "<?php echo $this->getAjaxPudoUrl(); ?>";
var INTELIPOST_PICKUP_SET_QUOTE = "<?php echo $this->getAjaxSetQuote(); ?>";

</script>

